url: https://roadbook-recorder.github.io/
baseurl: /

# Site settings
title: Roadbook Recorder
email: your-email@domain.com
description: "A tool dedicated for automatic generation of roadbooks."


# Team names, titles and social links
people:
- name: Andrei David
  pic: 1
  position: Project Manger, Infrastucture
  social:
    - title: comment
      url: mailto:andrei.david0207@upb.ro
    - title: github
      url: https://github.com/dandrei279

- name: Ruxandra Grigorie
  pic: 2
  position: Public Relations, Android
  social:
    - title: comment
      url: mailto:ruxandra.grigore@stud.acs.upb.ro

- name: Iulia-Ana Tănăsescu
  pic: 3
  position: Public Relations
  social:
    - title: comment
      url: mailto:iulia.tanasescu56@gmail.com

- name: Nicolae-Iulian Nițu
  pic: 4
  position: Public Relations, Android
  social:
    - title: comment
      url: mailto:nitu.nicolae.1098@gmail.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/roadbook-recorder

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
